//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_SUBTYPE
    {
        public int Acc_subtype_Id { get; set; }
        public int AccTypeId { get; set; }
        public string NameSubType { get; set; }
    }
}
