//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_MSTR
    {
        public int Bank_Id { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string IFSC_Code { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string Branch { get; set; }
        public string Image { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string BankMasterCode { get; set; }
    }
}
