//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_INWARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL_INWARD()
        {
            this.BILL_INWARD_PARTICULARDETAILS = new HashSet<BILL_INWARD_PARTICULARDETAILS>();
        }
    
        public int Bill_Id { get; set; }
        public Nullable<int> Form_id { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public byte[] Attachment { get; set; }
        public string VendorName { get; set; }
        public string DeptName { get; set; }
        public string PSNNO { get; set; }
        public string Work_Order_NO { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> NetAmountPayble { get; set; }
        public Nullable<decimal> Status { get; set; }
    
        public virtual FORM_DETAILS FORM_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_INWARD_PARTICULARDETAILS> BILL_INWARD_PARTICULARDETAILS { get; set; }
    }
}
