//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_INWARD_PARTICULARDETAILS
    {
        public int Bill_PD_Id { get; set; }
        public int Bill_Id { get; set; }
        public string AccountCode { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Quanity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Description { get; set; }
    
        public virtual BILL_INWARD BILL_INWARD { get; set; }
    }
}
