//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARTOFACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHARTOFACCOUNT()
        {
            this.ACCOUNTPOSTINGs = new HashSet<ACCOUNTPOSTING>();
        }
    
        public int Acc_Id { get; set; }
        public string ACC_Code { get; set; }
        public string Narration { get; set; }
        public string AccountType { get; set; }
        public int AccTypeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string subgroup { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Acc_subtype_Id { get; set; }
        public string FunctionCode { get; set; }
        public string ObjectCode { get; set; }
        public string FunctionCodeDescription { get; set; }
        public string ObjectCodeDescription { get; set; }
    
        public virtual ACCOUNT_TYPE ACCOUNT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNTPOSTING> ACCOUNTPOSTINGs { get; set; }
    }
}
