//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_MSTR
    {
        public int CompanyId { get; set; }
        public string Comp_code { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string States { get; set; }
        public string EMail { get; set; }
        public string Mobile_number { get; set; }
        public string Pancard { get; set; }
        public string GST_Number { get; set; }
        public string Company_Type { get; set; }
        public Nullable<System.DateTime> Company_Formation_Date { get; set; }
        public string CIN_Number { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.DateTime> Validfrom { get; set; }
        public Nullable<int> No_User_Allowed { get; set; }
        public string Status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role_assign { get; set; }
        public byte[] Image { get; set; }
    }
}
