//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT_MASTER
    {
        public int DepId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DepartmentName { get; set; }
        public string AuthorizePersonName { get; set; }
        public Nullable<decimal> Status { get; set; }
    }
}
