//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM12_WO_REGISTER
    {
        public int Form12_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProjectName { get; set; }
        public string Work_Order_No { get; set; }
        public string Ref_WIP_Register { get; set; }
        public Nullable<decimal> Estimated_Cost { get; set; }
        public Nullable<decimal> Tender_Cost { get; set; }
        public Nullable<decimal> Sanctioned_Tender_Rates { get; set; }
        public Nullable<System.DateTime> Planned_completion_date { get; set; }
        public string Total_Work_value { get; set; }
        public string EMD_Receipt_No { get; set; }
        public Nullable<decimal> EMD_Amount { get; set; }
        public string SD_Receipt_No { get; set; }
        public Nullable<System.DateTime> Actual_date_completion { get; set; }
        public string Completion_certificate_No { get; set; }
        public string Remark { get; set; }
        public byte[] Signature { get; set; }
        public string Sanctioned_Year { get; set; }
        public Nullable<int> VendorNameId { get; set; }
        public Nullable<decimal> SD_Amount { get; set; }
        public Nullable<decimal> Status { get; set; }
    }
}
