//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM64_PAYMENTVOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORM64_PAYMENTVOUCHER()
        {
            this.FORM64_PARTICULARDETAILS = new HashSet<FORM64_PARTICULARDETAILS>();
        }
    
        public int Form64_Id { get; set; }
        public Nullable<int> Form_id { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Bill_No { get; set; }
        public string Bill_Details { get; set; }
        public string NamePayeeVendorContractor { get; set; }
        public Nullable<int> Form12_Id { get; set; }
        public Nullable<decimal> First_Advance { get; set; }
        public Nullable<decimal> Running_Amount { get; set; }
        public Nullable<decimal> Final_Amount { get; set; }
        public Nullable<decimal> GrossAmtPayable { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> Net_AmtPayable { get; set; }
        public string Amt_inwords { get; set; }
        public string Budget_provision { get; set; }
        public string Budget_code { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> BillPaid_tillnow { get; set; }
        public string Measurementbookreference { get; set; }
        public string No_of_stock { get; set; }
        public string current_billamt { get; set; }
        public string Book_No { get; set; }
        public Nullable<decimal> passed_paymentamt { get; set; }
        public string payment_inwords { get; set; }
        public string Work_Order_No { get; set; }
        public string Bank { get; set; }
        public string ChequeNo { get; set; }
        public string PSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORM64_PARTICULARDETAILS> FORM64_PARTICULARDETAILS { get; set; }
    }
}
