//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNALVOUCHER
    {
        public int JV_Id { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> JVDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountType { get; set; }
        public string Narration { get; set; }
        public Nullable<int> Acc_subtype_Id { get; set; }
        public string VoucherNo { get; set; }
        public string Description { get; set; }
    }
}
