//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class waroraEntities : DbContext
    {
        public waroraEntities()
            : base("name=waroraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<ACCOUNT_SUBTYPE> ACCOUNT_SUBTYPE { get; set; }
        public virtual DbSet<ACCOUNT_TYPE> ACCOUNT_TYPE { get; set; }
        public virtual DbSet<ACCOUNTPOSTING> ACCOUNTPOSTINGs { get; set; }
        public virtual DbSet<BANK_MSTR> BANK_MSTR { get; set; }
        public virtual DbSet<BILL_INWARD> BILL_INWARD { get; set; }
        public virtual DbSet<BILL_INWARD_PARTICULARDETAILS> BILL_INWARD_PARTICULARDETAILS { get; set; }
        public virtual DbSet<BRANCH_MSTR> BRANCH_MSTR { get; set; }
        public virtual DbSet<CHARTOFACCOUNT> CHARTOFACCOUNTs { get; set; }
        public virtual DbSet<COMPANY_MSTR> COMPANY_MSTR { get; set; }
        public virtual DbSet<COMPANYDIRECTOR_MSTR> COMPANYDIRECTOR_MSTR { get; set; }
        public virtual DbSet<DEPARTMENT_MASTER> DEPARTMENT_MASTER { get; set; }
        public virtual DbSet<DOCUMENT_TYPE> DOCUMENT_TYPE { get; set; }
        public virtual DbSet<FORM_DETAILS> FORM_DETAILS { get; set; }
        public virtual DbSet<FORM12_WO_REGISTER> FORM12_WO_REGISTER { get; set; }
        public virtual DbSet<FORM64_DEDUCTION> FORM64_DEDUCTION { get; set; }
        public virtual DbSet<FORM64_PARTICULARDETAILS> FORM64_PARTICULARDETAILS { get; set; }
        public virtual DbSet<FORM64_PAYMENTVOUCHER> FORM64_PAYMENTVOUCHER { get; set; }
        public virtual DbSet<FORM84_DETAIL_ESTIMATE> FORM84_DETAIL_ESTIMATE { get; set; }
        public virtual DbSet<FORM84_PARTICULARDETAILS> FORM84_PARTICULARDETAILS { get; set; }
        public virtual DbSet<FUNCTIONCODE> FUNCTIONCODEs { get; set; }
        public virtual DbSet<JOURNALVOUCHER> JOURNALVOUCHERs { get; set; }
        public virtual DbSet<OBJECTCODE> OBJECTCODEs { get; set; }
        public virtual DbSet<OPENING_BALANCE> OPENING_BALANCE { get; set; }
        public virtual DbSet<ROLE_MSTR> ROLE_MSTR { get; set; }
        public virtual DbSet<SESSION_MSTR> SESSION_MSTR { get; set; }
        public virtual DbSet<USER_MSTR> USER_MSTR { get; set; }
        public virtual DbSet<VENDOR_MSTR> VENDOR_MSTR { get; set; }
    }
}
