//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECTCODE
    {
        public int S_No { get; set; }
        public string Objectcode1 { get; set; }
        public string ObjectDescription { get; set; }
        public string Majorhead { get; set; }
        public string Minorhead { get; set; }
        public string DetailedHead { get; set; }
        public string Accounttype { get; set; }
    }
}
