//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPENING_BALANCE
    {
        public int OPBID { get; set; }
        public string YearId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalDr { get; set; }
        public Nullable<decimal> TotalCr { get; set; }
    }
}
